name: gofordevops

on:
  push:
    branches: [master]

jobs:

  gofordevops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Verify dependencies
        working-directory: ./chapter10/discovery
        run: go mod verify

      - name: Run tests
        working-directory: ./chapter10/discovery
        run: go test -v .

      - name: Verify dependencies
        working-directory: ./chapter10/securecom
        run: go mod verify

      - name: Run tests
        working-directory: ./chapter10/securecom
        run: go test -v .